/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: packages/ui/src/theme.ts
 * Command: astryx theme build packages/ui/src/theme.ts
 * Generated: 2026-08-05T04:10:09.198Z
 */

// Generated by astryx theme build
export {};

declare module "@astryxdesign/core/Badge" {
  interface BadgeVariantMap {
    gray: true;
  }
}
