/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: packages/ui/src/theme.ts
 * Command: astryx theme build packages/ui/src/theme.ts
 * Generated: 2026-08-05T04:10:09.202Z
 */

/// <reference path="./ssakmail.variants.d.ts" />
import type { DefinedTheme } from "@astryxdesign/core/theme";
export declare const ssakmailTheme: DefinedTheme;
